---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: ["--config", ".github/linters/.hadolint.yaml"]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
    - id: markdownlint
      args: ["--config", ".github/linters/.markdown-lint.yaml"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--rcfile=.github/linters/.python-lint"]
      - id: embedme
        name: embedme
        entry: npx
        language: system
        args: ["embedme", "README.md"]
